export const dataCategory1 = [
  {
    id: 'Cigrettes_abc123',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#D6EFF6',
    title: 'Cigrettes',
  },
  {
    id: 'Category_def456',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#F0E5D7',
    title: 'Category 2',
  },
  {
    id: 'Product_ghi789',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#A1B2C3',
    title: 'Product 3',
  },
  {
    id: 'Icon_jkl012',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#F8D6A1',
    title: 'Icon 4',
  },
  {
    id: 'Graphic_mno345',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#C9E1B3',
    title: 'Graphic 5',
  },
  {
    id: 'Design_pqr678',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#E5D6F0',
    title: 'Design 6',
  },
  {
    id: 'Illustration_stu901',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#B3C1A9',
    title: 'Illustration 7',
  },
  {
    id: 'Art_vwx234',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#D7F6EF',
    title: 'Art 8',
  },
  {
    id: 'Style_yz015',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#F0E5D7',
    title: 'Style 9',
  },
  {
    id: 'Fashion_678abc',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#A1B2C3',
    title: 'Fashion 10',
  },
  {
    id: 'Trend_901def',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#F8D6A1',
    title: 'Trend 11',
  },
  {
    id: 'Style_234ghi',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#C9E1B3',
    title: 'Style 12',
  },
];

export const dataCategory2 = [
  {
    id: 'Electronics_123abc',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#D6EFF6',
    title: 'Electronics',
  },
  {
    id: 'Books_def456',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#F0E5D7',
    title: 'Books',
  },
  {
    id: 'Music_ghi789',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#A1B2C3',
    title: 'Music',
  },
  {
    id: 'Sports_jkl012',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#F8D6A1',
    title: 'Sports',
  },
  {
    id: 'Food_mno345',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#C9E1B3',
    title: 'Food',
  },
  {
    id: 'Travel_pqr678',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#E5D6F0',
    title: 'Travel',
  },
  {
    id: 'Health_stu901',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#B3C1A9',
    title: 'Health',
  },
  {
    id: 'Home_vwx234',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#D7F6EF',
    title: 'Home',
  },
  {
    id: 'Fashion_yz015',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#F0E5D7',
    title: 'Fashion',
  },
  {
    id: 'Beauty_678abc',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#A1B2C3',
    title: 'Beauty',
  },
  {
    id: 'Gaming_901def',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#F8D6A1',
    title: 'Gaming',
  },
  {
    id: 'Art_234ghi',
    icon: 'https://mojoestore.myanmaronlinecreations.com/storage/category/cigarettes%201.svg',
    background: '#C9E1B3',
    title: 'Art',
  },
];

export const productData = [
  {
    id: 'Product_001',
    productName: 'Laptop',
    units: 10,
    price: '200 MMK/ unit',
    pricePerUnit: 200,
    qty: 1,
  },
  {
    id: 'Product_002',
    productName: 'Smartphone',
    units: 15,
    price: '600 MMK/ unit',
    pricePerUnit: 600,
    qty: 1,
  },
  {
    id: 'Product_003',
    productName: 'Headphones',
    units: 20,
    price: '100 MMK/ pair',
    pricePerUnit: 50,
    qty: 1,
  },
  {
    id: 'Product_004',
    productName: 'Digital Camera',
    units: 5,
    price: '1200 MMK/ unit',
    pricePerUnit: 1200,
    qty: 1,
  },
  {
    id: 'Product_005',
    productName: 'External Hard Drive',
    units: 8,
    price: '500 MMK/ unit',
    pricePerUnit: 500,
    qty: 1,
  },
  {
    id: 'Product_006',
    productName: 'Wireless Mouse',
    units: 12,
    price: '50 MMK/ unit',
    pricePerUnit: 50,
    qty: 1,
  },
  {
    id: 'Product_007',
    productName: 'Tablet',
    units: 18,
    price: '700 MMK/ unit',
    pricePerUnit: 700,
    qty: 1,
  },
  {
    id: 'Product_008',
    productName: 'Fitness Tracker',
    units: 25,
    price: '300 MMK/ unit',
    pricePerUnit: 300,
    qty: 1,
  },
  {
    id: 'Product_009',
    productName: 'Bluetooth Speaker',
    units: 7,
    price: '150 MMK/ unit',
    pricePerUnit: 150,
    qty: 1,
  },
  {
    id: 'Product_010',
    productName: 'Gaming Mouse',
    units: 9,
    price: '120 MMK/ unit',
    pricePerUnit: 120,
    qty: 1,
  },
  {
    id: 'Product_011',
    productName: 'Coffee Maker',
    units: 14,
    price: '900 MMK/ unit',
    pricePerUnit: 900,
    qty: 1,
  },
  {
    id: 'Product_012',
    productName: 'Portable Charger',
    units: 22,
    price: '250 MMK/ unit',
    pricePerUnit: 250,
    qty: 1,
  },
];
